[RORDEV-655] Ror kibana rule and JWT auth rule with "groups_and" support
sscarduzio/elasticsearch-readonlyrest-plugin pull request #820
Opened 2022-06-08 16:14 UTC by mateuszkp96

🚀New (ES) Added `groups_and` sub-rule for `ror_kbn_auth`, and `jwt_auth`

2022-06-09 17:10 UTC, coutoPL requested changes
and:
1. please add chanelog style description to the PR desc
2. don't forget about docs

2022-06-09 17:10 UTC, coutoPL commented on core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/JwtAuthRule.scala
> +              case GroupsLogic.Defined(strategy) if strategy.availableGroupsFrom(UniqueList.of(group)).isDefined =>
`strategy.groups.contains(group)` we don't need to check here based on strategy (so the `groups` extension method will be needed)

2022-06-09 17:10 UTC, coutoPL commented on core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/RorKbnAuthRule.scala
> +            case GroupsLogic.Defined(strategy) if strategy.availableGroupsFrom(UniqueList.of(group)).isDefined =>
the same here

2022-06-09 17:10 UTC, coutoPL commented on tests-utils/src/main/scala/tech/beshu/ror/utils/httpclient/RestClient.scala
> +    val sslsf = new SSLConnectionSocketFactory(sslCtxBuilder.build(), NoopHostnameVerifier.INSTANCE);
why do we need to change it?

2022-06-11 11:47 UTC, mateuszkp96 commented on tests-utils/src/main/scala/tech/beshu/ror/utils/httpclient/RestClient.scala
> +    val sslsf = new SSLConnectionSocketFactory(sslCtxBuilder.build(), NoopHostnameVerifier.INSTANCE);
I fixed deprecation warning

2022-06-11 13:22 UTC, coutoPL approved these changes
LGTM

2022-06-11 13:23 UTC, merged