RORDEV-774 Fix ro users visibility issues
sscarduzio/elasticsearch-readonlyrest-plugin pull request #861
Opened 2022-11-13 07:31 UTC by Dzuming

- Moving `"indices:data/write/bulk*"` to the `RO_ACTIONS` resolved various of issues with RO Kibana access user:
    - https://readonlyrest.atlassian.net/browse/RORDEV-774
    - https://readonlyrest.atlassian.net/browse/RORDEV-740
    - And also discover page visibility

I attached es plugin build with the fix to [this](https://readonlyrest.atlassian.net/browse/RORDEV-740) task

2022-11-13 09:20 UTC, coutoPL commented
hmm, this is not a RO action for sure. if it has to be moved to RO actions, maybe we should add a comment about why it has to be done like this? 

cc: @sscarduzio

2022-11-13 09:26 UTC, sscarduzio commented
Yes this write  bulk * in RO actions deserves a bit more explanation lol

2022-11-13 18:42 UTC, Dzuming commented
I added a comment, please check if it's understandable enough.

> hmm, this is not a RO action for sure.

Yeah, it seems strange, but for some reason Kibana needs to call this POST /bulk endpoint even only to display readable Dashboard, Discover, or canvas page 🤔. The question is, 

1. Don't we give RO Kibana access level users, too many privileges? If I understand correctly, based on [docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docs-bulk.html#docs-bulk), thanks to it he will be able to perform indexing and deleting operations 
2. Side question, how exactly does this RO read-only logic works? I mean, how and where this state is set, I couldn't find any logic in the kibana plugin, where this read-only kibana UI state is set 
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/9945753/201538616-07da0e40-4b7c-475f-9df1-82a1f8ee715a.png">

2022-11-13 19:45 UTC, coutoPL commented
The comment is fine for me. But IMO we should understand the behaviour better. Could you please investigate what exactly Kibana does? Maybe it's worth taking a look at the request body?

2022-11-13 21:45 UTC, sscarduzio commented
The RO access is found in the matching ACL block, then it comes down as user metadata on Kibana user login. Then, a class is added to the <body> via PKP injection so a bunch of CSS gets applied, and a ton of buttons get hidden.

Does this answer your side question?

2022-11-13 21:49 UTC, sscarduzio commented
A RO user should not be able to create,delete or modify canvas, dashboards, visualizations or anything else. They should in general be forced leave the Kibana in the state they found it. Minor exceptions apply like creating a short URL when they click share in dashboards or viz. Ro_strict should be denied that too.

2022-11-14 06:10 UTC, Dzuming commented
>  Maybe it's worth taking a look at the request body?

Based on request If I interpret it correctly, on `POST /_bulk` there is a custom script running which increments resolveCounter

```
post /_bulk?refresh=false&require_alias=true
{"update":{"_id":"legacy-url-alias:default:canvas-workpad:workpad-aa682b3d-dad0-41a0-897c-53a13ed6ee41","_index":".kibana_8.4.3","_source":true}}
{"script":{"source":"\n            if (ctx._source[params.type].disabled != true) {\n              if (ctx._source[params.type].resolveCounter == null) {\n                ctx._source[params.type].resolveCounter = 1;\n              }\n              else {\n                ctx._source[params.type].resolveCounter += 1;\n              }\n              ctx._source[params.type].lastResolved = params.time;\n              ctx._source.updated_at = params.time;\n            }\n          ","lang":"painless","params":{"type":"legacy-url-alias","time":"2022-11-14T05:43:49.464Z"}}}

[2022-11-14T05:43:49,481][DEBUG][t.b.r.a.l.AccessControlLoggingDecorator] [n1_it] checking request: 1564063085-1918047998#12050
[2022-11-14T05:43:49,482][DEBUG][t.b.r.a.b.r.AuthKeyRule  ] [n1_it] Attempting Login as: admin rc: 1564063085-1918047998#12050
[2022-11-14T05:43:49,482][DEBUG][t.b.r.a.b.Block          ] [n1_it] [KIBANA_SERVER] the request matches no rules in this block: { ID:1564063085-1918047998#12050, TYP:BulkRequest, CGR:<N/A>, USR:admin (attempted), BRS:true, KDX:null, ACT:indices:data/write/bulk, OA:127.0.0.1/32, XFF:172.17.0.1, DA:127.0.0.1/32, IDX:.kibana_infosec, MET:POST, PTH:/_bulk, CNT:{"update":{"_id":"legacy-url-alias:default:canvas-workpad:workpad-aa682b3d-dad0-41a0-897c-53a13ed6ee41","_index":".kibana_infosec","_source":true}}{"script":{"source":"\n            if (ctx._source[params.type].disabled != true) {\n              if (ctx._source[params.type].resolveCounter == null) {\n                ctx._source[params.type].resolveCounter = 1;\n              }\n              else {\n                ctx._source[params.type].resolveCounter += 1;\n              }\n              ctx._source[params.type].lastResolved = params.time;\n              ctx._source.updated_at = params.time;\n            }\n          ","lang":"painless","params":{"type":"legacy-url-alias","time":"2022-11-14T05:43:49.464Z"}}}, HDR:Accept-Charset=utf-8, Authorization=<OMITTED>, Host=localhost:9200, accept=application/vnd.elasticsearch+json; compatible-with=8, connection=close, content-length=723, content-type=application/vnd.elasticsearch+x-ndjson; compatible-with=8, elastic-apm-traceparent=00-50f2a716f7df3582efe70285832a5a9c-93294bb3c549f3c0-01, traceparent=00-50f2a716f7df3582efe70285832a5a9c-93294bb3c549f3c0-01, tracestate=es=s:0.1, user-agent=elastic-transport-js/8.2.0 (linux 5.10.25-linuxkit-arm64; Node.js v16.17.1), x-elastic-client-meta=es=8.3.0p,js=16.17.1,t=8.2.0,hc=16.17.1, x-elastic-product-origin=kibana, x-forwarded-for=172.17.0.1, x-opaque-id=unknownId, x-ror-correlation-id=2dd56c31-36fd-4cfb-a88e-397c168f4d00, x-ror-current-group=infosec, x-ror-kibana-request-method=get, x-ror-kibana-request-path=/s/default/api/canvas/workpad/resolve/workpad-aa682b3d-dad0-41a0-897c-53a13ed6ee41, HIS:[KIBANA_SERVER-> RULES:[auth_key->false] RESOLVED:[group=infosec;indices=.kibana_infosec]], }
[2022-11-14T05:43:49,483][DEBUG][t.b.r.a.b.Block          ] [n1_it] [PERSONAL_GRP] the request matches no rules in this block: { ID:1564063085-1918047998#12050, TYP:BulkRequest, CGR:<N/A>, USR:admin (attempted), BRS:true, KDX:null, ACT:indices:data/write/bulk, OA:127.0.0.1/32, XFF:172.17.0.1, DA:127.0.0.1/32, IDX:.kibana_infosec, MET:POST, PTH:/_bulk, CNT:{"update":{"_id":"legacy-url-alias:default:canvas-workpad:workpad-aa682b3d-dad0-41a0-897c-53a13ed6ee41","_index":".kibana_infosec","_source":true}}{"script":{"source":"\n            if (ctx._source[params.type].disabled != true) {\n              if (ctx._source[params.type].resolveCounter == null) {\n                ctx._source[params.type].resolveCounter = 1;\n              }\n              else {\n                ctx._source[params.type].resolveCounter += 1;\n              }\n              ctx._source[params.type].lastResolved = params.time;\n              ctx._source.updated_at = params.time;\n            }\n          ","lang":"painless","params":{"type":"legacy-url-alias","time":"2022-11-14T05:43:49.464Z"}}}, HDR:Accept-Charset=utf-8, Authorization=<OMITTED>, Host=localhost:9200, accept=application/vnd.elasticsearch+json; compatible-with=8, connection=close, content-length=723, content-type=application/vnd.elasticsearch+x-ndjson; compatible-with=8, elastic-apm-traceparent=00-50f2a716f7df3582efe70285832a5a9c-93294bb3c549f3c0-01, traceparent=00-50f2a716f7df3582efe70285832a5a9c-93294bb3c549f3c0-01, tracestate=es=s:0.1, user-agent=elastic-transport-js/8.2.0 (linux 5.10.25-linuxkit-arm64; Node.js v16.17.1), x-elastic-client-meta=es=8.3.0p,js=16.17.1,t=8.2.0,hc=16.17.1, x-elastic-product-origin=kibana, x-forwarded-for=172.17.0.1, x-opaque-id=unknownId, x-ror-correlation-id=2dd56c31-36fd-4cfb-a88e-397c168f4d00, x-ror-current-group=infosec, x-ror-kibana-request-method=get, x-ror-kibana-request-path=/s/default/api/canvas/workpad/resolve/workpad-aa682b3d-dad0-41a0-897c-53a13ed6ee41, HIS:[PERSONAL_GRP-> RULES:[groups->false] RESOLVED:[group=infosec;indices=.kibana_infosec]], }
[2022-11-14T05:43:49,483][DEBUG][t.b.r.a.b.Block          ] [n1_it] [ADMIN_GRP] the request matches no rules in this block: { ID:1564063085-1918047998#12050, TYP:BulkRequest, CGR:<N/A>, USR:admin (attempted), BRS:true, KDX:null, ACT:indices:data/write/bulk, OA:127.0.0.1/32, XFF:172.17.0.1, DA:127.0.0.1/32, IDX:.kibana_infosec, MET:POST, PTH:/_bulk, CNT:{"update":{"_id":"legacy-url-alias:default:canvas-workpad:workpad-aa682b3d-dad0-41a0-897c-53a13ed6ee41","_index":".kibana_infosec","_source":true}}{"script":{"source":"\n            if (ctx._source[params.type].disabled != true) {\n              if (ctx._source[params.type].resolveCounter == null) {\n                ctx._source[params.type].resolveCounter = 1;\n              }\n              else {\n                ctx._source[params.type].resolveCounter += 1;\n              }\n              ctx._source[params.type].lastResolved = params.time;\n              ctx._source.updated_at = params.time;\n            }\n          ","lang":"painless","params":{"type":"legacy-url-alias","time":"2022-11-14T05:43:49.464Z"}}}, HDR:Accept-Charset=utf-8, Authorization=<OMITTED>, Host=localhost:9200, accept=application/vnd.elasticsearch+json; compatible-with=8, connection=close, content-length=723, content-type=application/vnd.elasticsearch+x-ndjson; compatible-with=8, elastic-apm-traceparent=00-50f2a716f7df3582efe70285832a5a9c-93294bb3c549f3c0-01, traceparent=00-50f2a716f7df3582efe70285832a5a9c-93294bb3c549f3c0-01, tracestate=es=s:0.1, user-agent=elastic-transport-js/8.2.0 (linux 5.10.25-linuxkit-arm64; Node.js v16.17.1), x-elastic-client-meta=es=8.3.0p,js=16.17.1,t=8.2.0,hc=16.17.1, x-elastic-product-origin=kibana, x-forwarded-for=172.17.0.1, x-opaque-id=unknownId, x-ror-correlation-id=2dd56c31-36fd-4cfb-a88e-397c168f4d00, x-ror-current-group=infosec, x-ror-kibana-request-method=get, x-ror-kibana-request-path=/s/default/api/canvas/workpad/resolve/workpad-aa682b3d-dad0-41a0-897c-53a13ed6ee41, HIS:[ADMIN_GRP-> RULES:[groups->false] RESOLVED:[group=infosec;indices=.kibana_infosec]], }
[2022-11-14T05:43:49,484][DEBUG][t.b.r.a.b.r.AuthKeyRule  ] [n1_it] Attempting Login as: admin rc: 1564063085-1918047998#12050
[2022-11-14T05:43:49,485][DEBUG][t.b.r.a.b.r.KibanaHideAppsRule] [n1_it] setting hidden apps for user admin: Enterprise Search|Overview,Management,Observability
[2022-11-14T05:43:49,485][DEBUG][t.b.r.a.b.Block          ] [n1_it] matched { name: 'infosec', policy: ALLOW, rules: [groups,kibana_hide_apps,kibana_index,kibana_access] { found: user=admin;group=infosec;av_groups=infosec;indices=.kibana_infosec;kibana_idx=.kibana_infosec }
[2022-11-14T05:43:49,486][DEBUG][t.b.r.e.h.RegularRequest [...]

2022-11-14 09:51 UTC, sscarduzio commented
> I got it, thanks :) , one missing thing is this "read only" badge with, a tooltip message I can't find any place in the code where we are adding it

This is where we set the badge: public/components/rorMenu.tsx:189

<img width="448" alt="image" src="https://user-images.githubusercontent.com/1327189/201628448-d39229b1-3ac1-4aa9-b3e9-c742c234e45d.png">
<img width="381" alt="image" src="https://user-images.githubusercontent.com/1327189/201628555-c5d09cbc-7faa-4aa2-88ad-b1e90f778b5e.png">

The info comes from the identity section of the info API response. Which is served by PKP here:
proxy/preKibanaProxy/api/controller/infoController.ts:53

2022-11-14 13:48 UTC, Dzuming commented
> > I got it, thanks :) , one missing thing is this "read only" badge with, a tooltip message I can't find any place in the code where we are adding it
> 
> This is where we set the badge: public/components/rorMenu.tsx:189
> 
> <img alt="image" width="448" src="https://user-images.githubusercontent.com/1327189/201628448-d39229b1-3ac1-4aa9-b3e9-c742c234e45d.png">
> 
> <img alt="image" width="381" src="https://user-images.githubusercontent.com/1327189/201628555-c5d09cbc-7faa-4aa2-88ad-b1e90f778b5e.png">
> 
> The info comes from the identity section of the info API response. Which is served by PKP here: proxy/preKibanaProxy/api/controller/infoController.ts:53

Sorry, I meant this glasses icon badge :). 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/9945753/201676208-99bbba75-0674-4b0c-8ec9-33f8ff3bb5ef.png">

2022-11-14 17:40 UTC, sscarduzio commented
that shit is actual Kibana code! No way we wrote that.

2022-11-16 14:02 UTC, Dzuming commented
We discussed here https://beshu.slack.com/archives/C019VCTKYVD/p1668525361425599 that it's probably not the best approach to let RO user permission to the `POST /_bulk`. I will try to handle this case in the PEP. If we find the proper solution I will close this pr.

2022-11-21 20:24 UTC, coutoPL requested changes
ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/861#issuecomment-1317071877

2022-11-22 05:08 UTC, Dzuming commented
We can close it since there is a pending pr [here](https://github.com/sscarduzio/readonlyrest_kbn/pull/359)

2022-11-22 05:08 UTC, closed without merging