[RORDEV-1079] fix: Repositories and Snapshots handling by ES coordinating nodes
sscarduzio/elasticsearch-readonlyrest-plugin pull request #993
Opened 2024-03-13 20:45 UTC by coutoPL

🐞Fix (ES) [Repositories and Snapshots handling by ES coordinating nodes](https://forum.readonlyrest.com/t/snapshot-status-cannot-modify-incoming-request/2471)

2024-03-13 22:07 UTC, mateuszkp96 requested changes

2024-03-14 19:18 UTC, mk-software-pl commented on es65x/src/main/scala/tech/beshu/ror/es/utils/EsPatchVerifier.scala
> +          throw new IllegalStateException("Elasticsearch is not patched. ReadonlyREST cannot be started. For patching instructions see our docs: https://docs.readonlyrest.com/elasticsearch#3.-patch-e
there is no cats-core in the ror-tools, so I didn't use Show typeclass. I think there is no need to add it now.

2024-03-14 19:19 UTC, coutoPL commented on es65x/src/main/scala/tech/beshu/ror/es/utils/EsPatchVerifier.scala
> +          throw new IllegalStateException("Elasticsearch is not patched. ReadonlyREST cannot be started. For patching instructions see our docs: https://docs.readonlyrest.com/elasticsearch#3.-patch-e
there is not cats-core in the ror-tools so I didn't use Show typeclass. IMO there is no sense to add the dependency

2024-03-14 19:22 UTC, coutoPL commented on es63x/src/main/scala/tech/beshu/ror/es/utils/EsPatchVerifier.scala
> +    } yield esPatch.isPatched match {
I removed the patching step from the `es63x` module. It's too problematic to support and I think in the near future we will remove the following modules: `es60x`, `es61x`, `es62x` & `es63x`

2024-03-14 19:50 UTC, mateuszkp96 approved these changes
LGTM

2024-03-15 13:06 UTC, merged